require("core.lazy")
require("core.config")
require("core.keymaps")

require("plugins.theme")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.hop")
require("plugins.autopairs")
require("plugins.comments")
