require("core.lazy")
require("core.mappings")
require("core.config")

require("plugins.theme")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.hop")
